# Overrides for kanban-app values
app:
  configMapData:
    DB_SERVER: kanban-postgres
    POSTGRES_DB: kanban
    POSTGRES_USER: kanban
  secretMapData:
    POSTGRES_PASSWORD: kanban

# Overrides for kanban-ui values
ui: {}

# Overrides for bitnami/postgresql values
postgresql:
  postgresqlDatabase: kanban
  postgresqlPostgresPassword: kanban
  postgresqlUsername: kanban
  postgresqlPassword: kanban
  fullnameOverride: kanban-postgres  # Set name to the same as from docker-compose.
