version: '3'
services:
  kanban-postgres:
    container_name: kanban-postgres
    build: ./kanban-postgres
    volumes:
      - kanban-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  kanban-app:
    build: ./kanban-app
    environment:
      - DB_SERVER=kanban-postgres
    ports:
      - "8080:8080"
    links:
      - kanban-postgres



volumes:
  kanban-data:
