{{ if or .Values.secretMapData .Values.secretMapB64Data }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "kanban-ui.fullname" . }}-secrets
  labels:
    {{- include "kanban-ui.labels" . | nindent 4 }}
data:
{{- range $k, $v := .Values.secretMapData }}
  {{ $k }}: {{ $v | b64enc }}
{{- end }}
{{- range $k, $v := .Values.secretMapB64Data }}
  {{ $k }}: {{ $v }}
{{- end }}
{{- end }}