# Overrides for kanban-app values
app:
  configMapData:
    DB_SERVER: kanban-postgres
    POSTGRES_DB: kanban
    POSTGRES_USER: kanban
  secretMapData:
    POSTGRES_PASSWORD: kanban
  replicaCount: 2

# Overrides for kanban-ui values
ui:
  # When using minikube run `minikube addons enable ingress` 
  # and add the ingress IP to to your hosts file
  # echo "$(kubectl get ingress/kanban-ui --output jsonpath='{.status.loadBalancer.ingress[0].ip}') kanban.example" >> /etc/hosts
  ingress:
    enabled: true
    hosts:
    - host: kanban.example
      paths:
      - path: "/"
        pathType: Prefix
  replicaCount: 4

# Overrides for bitnami/postgresql values
postgresql:
  postgresqlDatabase: kanban
  postgresqlPostgresPassword: kanban
  postgresqlUsername: kanban
  postgresqlPassword: kanban
  fullnameOverride: kanban-postgres  # Set name to the same as from docker-compose.
