name: ci

on:
  push:
    branches:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: ls -l
      
      - name: Compile variables
        shell: bash
        id: compile_variables
        run: |
          echo "::set-output name=KANBAN_APP_VER::$(cat kanban-app/Chart.yaml | grep -oP 'appVersion: \"(\K.*)(?=\")')"
          echo "::set-output name=KANBAN_UI_VER::$(cat kanban-ui/Chart.yaml | grep -oP 'appVersion: \"(\K.*)(?=\")')"
          echo "::set-output name=COMMIT_SHA_SHORT::$(echo ${GITHUB_SHA::8})"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push kanban-app
        id: app_docker_build
        uses: docker/build-push-action@v2
        with:
          context: kanban-app/
          push: true
          tags: moreytech/kanban-board-k8s-demo:app-latest,moreytech/kanban-board-k8s-demo:${{ steps.compile_variables.outputs.KANBAN_APP_VER }},moreytech/kanban-board-k8s-demo:app-${{ steps.compile_variables.outputs.COMMIT_SHA_SHORT }}
      - name: Image digest
        run: echo ${{ steps.app_docker_build.outputs.digest }}
      
      - name: Build and push kanban-ui
        id: ui_docker_build
        uses: docker/build-push-action@v2
        with:
          context: kanban-ui/
          push: true
          tags: moreytech/kanban-board-k8s-demo:ui-latest,moreytech/kanban-board-k8s-demo:${{ steps.compile_variables.outputs.KANBAN_UI_VER }},moreytech/kanban-board-k8s-demo:ui-${{ steps.compile_variables.outputs.COMMIT_SHA_SHORT }}
      - name: Image digest
        run: echo ${{ steps.ui_docker_build.outputs.digest }}